# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

# Code coverage report
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

# Deploy static docs; https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
